server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /home/<user>/portfolio;
    index index.html;
    server_name dahirabdirahman.com www.dahirabdirahman.com;
    location / {
        try_files $uri $uri/ =404;
    }
}
